### ISSUE TITLE
音量調節バーの表示が振り切れる

### ISSUE THREAD

**Issue by mopp** [abouthiroppy/nicohaco#1]
音量調節バーを右へ持っていくと、曲情報と被って表示されます
音量自体はある程度で最大になって、それ以上大きくはならないです
<img width="489" alt="2017-05-29 12 25 37" src="https://cloud.githubusercontent.com/assets/1330045/26535596/fd8caff2-4469-11e7-8389-0885cad29cc2.png">

**Comment by hiroppy** [comment]
media-queryで書き直します
