### ISSUE TITLE
【マイリスト画面】投稿日時が"00"月になってしまう場合がある

### ISSUE THREAD

**Issue by c-ardinal** [abouthiroppy/nicohaco#15]
<img width="1000" alt="2018-02-05 21 09 11" src="https://user-images.githubusercontent.com/15723021/35808378-efa13a36-0ac8-11e8-9320-f06af6ce53f1.png">

【環境】
NicoHaco v1.0.0 Mac版 & Win版
macOS 10.13.1
Windows 10

【内容】
・"06", "07", "09"月の時だけ"00"月表記になる
・他のマイリストも確認したが，同様に上記の月だけ"00"月表記になっていた
・マイリストだと日付表記がおかしい動画を"My Page"の"History"や検索結果画面で見ると正しく表示される
・Windows版およびMac版両方試したがどちらでも発生した

**Comment by hiroppy** [comment]
ありがとうございます。修正します

**Comment by hiroppy** [comment]
v1.0.2にて修正しました。 https://github.com/nicohaco/nicohaco/releases/tag/v1.0.2

**Comment by c-ardinal** [comment]
修正されているのを確認しました。ありがとうございます‼👍
