### ISSUE TITLE
マイリストの日付がおかしい

### ISSUE THREAD

**Issue by mopp** [abouthiroppy/nicohaco#2]
<img width="438" alt="2017-05-29 12 38 08" src="https://cloud.githubusercontent.com/assets/1330045/26535814/bd9f2ef4-446b-11e7-8195-c4b4e38a755a.png">

* 日付自体がずれている
* 日付の表示フォーマットが不自然

**Comment by hiroppy** [comment]
ありがとうございます。
`* 1000` しわすれですね。修正します

**Comment by hiroppy** [comment]
修正されましたので閉じます
