### ISSUE TITLE
NICOHACO or NICOHAKO

### ISSUE THREAD

**Issue by ln-north** [abouthiroppy/nicohaco#4]
ロゴは `NICOHACO` だが、リポジトリ名などは `NICOHAKO`、どちらが正しいでしょうか…?

**Comment by hiroppy** [comment]
NicoHaco です(書いているうちに気づかず変わっていた😅)

**Comment by ln-north** [comment]
おお、リポジトリ名が変わった！応援しております 👍

**Comment by hiroppy** [comment]
ありがとうございます！

**Comment by hiroppy** [comment]
全てNicoHacoへ変更しました;)

**Comment by ln-north** [comment]
:clap:
